### ISSUE TITLE
(deb installer) dependencies insufficient

### ISSUE THREAD

**Issue by bertsky** [schorschii/CertUploader#2]
I get
```
Traceback (most recent call last):
  File "/usr/bin/certuploader", line 18, in <module>
    from cryptography.hazmat.primitives.serialization import pkcs12
ImportError: cannot import name 'pkcs12'
```

Indeed, the system package python3-cryptography, pulled via
https://github.com/schorschii/CertUploader/blob/021394102560d8f10134722e91eb50a9fc8704d0/installer/debian/certuploader/DEBIAN/control#L6

gets installed in version 2.1.4 – too old for PKCS, which according to that package's changelog requires at least [v2.5](https://cryptography.io/en/latest/changelog/#v2-5) or [v3.0](https://cryptography.io/en/latest/changelog/#v3-0).

So the Debian package should contain a corresponding version range.

**Comment by schorschii** [comment]
Which distro are you using? The package was tested with both currently supported Ubuntu versions 20.04 (python3-cryptography = 2.8) and Ubuntu 22.04 (python3-cryptography = 3.4.8).
